apiVersion: v1
kind: Service
metadata:
  name: digicart-ecom-service
spec:
  selector:
    app: digicart-ecom  # This should match the `app` label in your Deployment
  ports:
    - protocol: TCP
      port: 80           # External port (standard HTTP port)
      targetPort: 3003    # Port on the container where your app is running
      nodePort: 30007     # NodePort for external access; Kubernetes will map this port
  type: NodePort           # Type of Service to allow external access via a node's IP
